### ISSUE TITLE
CT Perennial task failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/simula-rasa#27] opened 2022-08-24 16:57 UTC
```
simula-rasa : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> tsc complete: 97150ms
Building runnable repository (simula-rasa, brands: phet)
Building brand: phet
>> Webpack build complete: 21958ms
>> Unused string: key=simula-rasa.title, value={{TITLE}}
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: missing entry for sim title, key = SIMULA_RASA/simula-rasa.title
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1661305124647/chipper/js/grunt/buildRunnable.js:152:3)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async /data/share/phet/continuous-testing/ct-snapshots/1661305124647/chipper/js/grunt/Gruntfile.js:306:11
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1661305124647/chipper/js/grunt/Gruntfile.js:65:7)
Full Error details:
AssertionError [ERR_ASSERTION]: missing entry for sim title, key = SIMULA_RASA/simula-rasa.title
Snapshot from 8/23/2022, 7:38:44 PM
```

**Comment by pixelzoom** [comment] 2022-08-24 17:42
This was caused by https://github.com/phetsims/simula-rasa/issues/26, where simulaRasaStrings.ts was renamed to SimulaRasaStrings.ts.   The build tools require camelCase, not PascalCase.  

@marlitas please address https://github.com/phetsims/simula-rasa/issues/26, then confirm that `grunt build` works for simula-rasa.

**Comment by pixelzoom** [comment] 2022-08-27 21:23
Addressed by reverting https://github.com/phetsims/simula-rasa/issues/26.  Closing.

**Closed by pixelzoom** 2022-08-27 21:23 UTC
Labels: type:automated-testing
